# Generated by Django 6.0.7 on 2026-08-07 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruitment', '0005_application_rejected_at_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('10th', 'SSC / 10th'), ('12th', 'HSC / 12th'), ('diploma', 'Diploma'), ('ug', 'Graduate (UG)'), ('pg', 'Post-graduate (PG)'), ('other', 'Other')], max_length=20)),
                ('discipline', models.CharField(blank=True, max_length=200)),
                ('university_board', models.CharField(blank=True, max_length=200)),
                ('year_passed', models.PositiveIntegerField(blank=True, null=True)),
                ('marking_type', models.CharField(choices=[('percentage', 'Percentage'), ('cgpa', 'CGPA'), ('grade', 'Grade')], default='percentage', max_length=20)),
                ('score', models.CharField(blank=True, max_length=20)),
                ('is_ugc_recognized', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='recruitment.candidate')),
            ],
            options={
                'ordering': ['-year_passed'],
            },
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('category', models.CharField(blank=True, choices=[('ur', 'UR'), ('obc', 'OBC (NCL)'), ('sc', 'SC'), ('st', 'ST'), ('ews', 'EWS')], max_length=10)),
                ('is_pwbd', models.BooleanField(default=False)),
                ('aadhar_no', models.CharField(blank=True, help_text='Aadhaar number (proof document required)', max_length=20)),
                ('permanent_address', models.TextField(blank=True)),
                ('current_address', models.TextField(blank=True)),
                ('current_same_as_permanent', models.BooleanField(default=False, help_text='Check to reuse the permanent address as the current address.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='recruitment.candidate')),
            ],
            options={
                'verbose_name': 'Candidate Profile',
            },
        ),
        migrations.CreateModel(
            name='ExamDisclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(blank=True, choices=[('gate', 'GATE'), ('ese', 'ESE'), ('both', 'GATE + ESE')], max_length=10)),
                ('gate_year', models.PositiveIntegerField(blank=True, null=True)),
                ('paper_code', models.CharField(blank=True, max_length=20)),
                ('marks_out_100', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gate_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('air', models.PositiveIntegerField(blank=True, help_text='All India Rank', null=True)),
                ('ese_total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('public_disclosure_consent', models.BooleanField(default=False, help_text='Consent to disclose the score publicly in the merit list.')),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_disclosure', to='recruitment.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('dob', 'Date of Birth Proof'), ('aadhar', 'Aadhaar'), ('academic', 'Academic Record'), ('work_ex', 'Work Experience'), ('public_exam', 'Public Exam Score'), ('certificate', 'Certificate'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='profile_documents/')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_documents', to='recruitment.candidate')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=200)),
                ('org_type', models.CharField(blank=True, choices=[('psu', 'PSU'), ('private', 'Private'), ('govt', 'Government'), ('other', 'Other')], max_length=20)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('annual_ctc_lakhs', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('turnover_cr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='recruitment.candidate')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
