# Generated by Django 6.0.7 on 2026-08-08 11:27

import profiles.fields
from django.db import migrations, models


def encrypt_existing_aadhar(apps, schema_editor):
    # Field is still CharField here: plaintext is read directly, then re-saved
    # through the ORM field (now EncryptedTextField would double-encrypt, so
    # encrypt explicitly and store ciphertext via raw value).
    CandidateProfile = apps.get_model("profiles", "CandidateProfile")
    from profiles.fields import _fernet

    for profile in CandidateProfile.objects.exclude(aadhar_no="").exclude(aadhar_no=None):
        plain = profile.aadhar_no
        if plain and not plain.startswith("gAAAA"):
            profile.aadhar_no = _fernet().encrypt(plain.encode()).decode()
            profile.save(update_fields=["aadhar_no"])


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='aadhar_retention_date',
            field=models.DateField(blank=True, help_text='Scheduled purge date for Aadhaar data.', null=True),
        ),
        migrations.RunPython(encrypt_existing_aadhar, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='candidateprofile',
            name='aadhar_no',
            field=profiles.fields.EncryptedTextField(blank=True, help_text='Aadhaar number (proof document required) — encrypted at rest.'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('ur', 'General (UR)'), ('obc', 'OBC (NCL)'), ('sc', 'SC'), ('st', 'ST'), ('ews', 'EWS')], max_length=10),
        ),
    ]
