# Generated by Django 6.0.7 on 2026-08-04 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('advt_number', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('published_date', models.DateField()),
                ('closing_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('document_verification', 'Document Verification'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('offered', 'Offered'), ('joined', 'Joined'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='received', max_length=30)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('employee_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalJobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('min_experience_years', models.PositiveIntegerField(default=0)),
                ('deputation_eligible', models.BooleanField(default=False)),
                ('open_from', models.DateField()),
                ('open_until', models.DateField()),
                ('priority_flag', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackgroundReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facts', models.JSONField(blank=True, default=dict)),
                ('candidate_explanation', models.TextField(blank=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('explained', 'Candidate Explained'), ('reviewed', 'Reviewed')], default='pending', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='background_report', to='recruitment.application')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portal_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='portal.candidateportaluser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.candidate'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='documents/')),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='recruitment.application')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DuplicateFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.PositiveSmallIntegerField(default=0, help_text='0-100 match confidence.')),
                ('match_fields', models.JSONField(blank=True, default=list)),
                ('resolution', models.CharField(choices=[('pending', 'Pending'), ('genuine_duplicate', 'Genuine Duplicate'), ('false_positive', 'False Positive'), ('merged', 'Merged')], default='pending', max_length=30)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='recruitment.application')),
                ('application_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='recruitment.application')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_flags', to='recruitment.candidate')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('post_code', models.CharField(max_length=50)),
                ('vacancies', models.PositiveIntegerField(default=1)),
                ('max_age', models.PositiveIntegerField(blank=True, null=True)),
                ('qualification', models.TextField()),
                ('experience_required', models.TextField(blank=True)),
                ('pay_scale', models.CharField(blank=True, max_length=100)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='recruitment.advertisement')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('advertisement', 'post_code')},
            },
        ),
        migrations.AddField(
            model_name='application',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.post'),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('parsed_json', models.JSONField(blank=True, null=True)),
                ('confidence', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('parse_status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='recruitment.candidate')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CategoryAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ur', 'UR'), ('obc', 'OBC (NCL)'), ('sc', 'SC'), ('st', 'ST'), ('ews', 'EWS'), ('pwbd', 'PwBD')], max_length=10)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='category_certificates/')),
                ('is_verified', models.BooleanField(default=False)),
                ('fills_slot', models.BooleanField(default=False, help_text='Set True at offer time to consume a roster slot.')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_allocations', to='recruitment.application')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('application', 'category')},
            },
        ),
        migrations.CreateModel(
            name='InternalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('current_grade', models.CharField(blank=True, max_length=50)),
                ('years_at_org', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_applications', to=settings.AUTH_USER_MODEL)),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.internaljobposting')),
            ],
            options={
                'unique_together': {('posting', 'applicant')},
            },
        ),
        migrations.CreateModel(
            name='PanelList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_rank', models.PositiveIntegerField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('promoted_on', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_entry', to='recruitment.application')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_list', to='recruitment.post')),
            ],
            options={
                'ordering': ['post', 'panel_rank'],
                'unique_together': {('post', 'application')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('post', 'candidate')},
        ),
        migrations.CreateModel(
            name='RosterMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ur', 'UR'), ('obc', 'OBC (NCL)'), ('sc', 'SC'), ('st', 'ST'), ('ews', 'EWS')], max_length=10)),
                ('vertical_vacancies', models.PositiveIntegerField(default=0)),
                ('pwbd_horizontal_vacancies', models.PositiveIntegerField(default=0)),
                ('carry_forward', models.BooleanField(default=False, help_text='Unfilled backlog to carry forward.')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_matrix', to='recruitment.post')),
            ],
            options={
                'ordering': ['post', 'category'],
                'unique_together': {('post', 'category')},
            },
        ),
    ]
