# Generated by Django 6.0.7 on 2026-08-04 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_application_evaluation_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('portal', 'Portal Notification')], default='portal', max_length=10)),
                ('comm_type', models.CharField(choices=[('acknowledgement', 'Application Acknowledgement'), ('status_update', 'Status Update'), ('interview_invite', 'Interview Invite'), ('offer', 'Offer Letter'), ('rejection', 'Rejection')], max_length=30)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='recruitment.application')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
