# Generated by Django 6.0.7 on 2026-08-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_communicationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='company_address',
            field=models.CharField(blank=True, default='Brookland Compound, Lower New Colony, Shillong – 793003, Meghalaya', max_length=300),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='company_name',
            field=models.CharField(blank=True, default='North Eastern Electric Power Corporation Limited', max_length=200),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='company_tagline',
            field=models.CharField(blank=True, default='(A Government of India Enterprise)', max_length=200),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='contact_email',
            field=models.CharField(blank=True, default='recruitment@neepco.co.in', max_length=120),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='general_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='health_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='how_to_apply',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='registration_fee_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='category_breakup',
            field=models.JSONField(blank=True, default=dict, help_text="e.g. {'ur': 2, 'ews': 0, 'obc': 1, 'sc': 0, 'st': 0}"),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, default='Shillong or any Offices/Project sites of NEEPCO, anywhere in India', max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='period_of_engagement',
            field=models.CharField(blank=True, default='Initially for 3 (three) years and extendable by further 2 (two) years on yearly basis based on the performance and requirement', max_length=300),
        ),
    ]
