# Generated by Django 6.0.7 on 2026-08-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_advertisement_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='rejected_at_stage',
            field=models.CharField(blank=True, choices=[('received', 'Received'), ('document_verification', 'Document Verification'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('offered', 'Offered'), ('joined', 'Joined'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], help_text='Stage at which the application was rejected/withdrawn (shown as a red X in the candidate stepper).', max_length=30, null=True),
        ),
    ]
