# Generated by Django 6.0.7 on 2026-08-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_application_rejected_at_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='required_certificates',
            field=models.JSONField(blank=True, default=list, help_text='Certificates applicants must upload (e.g. SAP, Primavera, GATE scorecard).'),
        ),
    ]
