# Generated by Django 6.0.7 on 2026-08-07 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_post_required_certificates'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=50)),
                ('issuer', models.CharField(blank=True, max_length=200)),
                ('issue_date', models.CharField(blank=True, max_length=30)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('signature_valid', models.BooleanField(default=False)),
                ('source', models.CharField(default='digilocker', max_length=20)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetched_documents', to='recruitment.application')),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
    ]
