# Generated by Django 6.0.7 on 2026-08-08 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_fetcheddocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='parse_error',
            field=models.TextField(blank=True, help_text="Parsing error message when parse_status='failed'."),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_schema', models.CharField(blank=True, default='', help_text='Tenant schema in which the change happened (schema == tenant identity).', max_length=63)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='recruitment.application')),
            ],
            options={
                'verbose_name': 'Audit Event',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['application', '-timestamp'], name='recruitment_applica_732269_idx')],
            },
        ),
    ]
