# Generated by Django 6.0.7 on 2026-08-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_resume_parse_error_auditevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200)),
                ('name_hi', models.CharField(blank=True, max_length=200)),
                ('tagline_en', models.CharField(blank=True, max_length=200)),
                ('tagline_hi', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('footer_motto', models.CharField(blank=True, max_length=300)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('sbi_epay_text', models.TextField(blank=True, help_text='Registration fee / SBI ePay payment instructions (moved from Advertisement.registration_fee_text).')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org_logos/')),
                ('accent_color', models.CharField(default='#0b3d91', help_text='CSS hex color (e.g. #0b3d91) used for portal accent theming.', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organisation Profile',
            },
        ),
    ]
