# Generated by Django 6.0.7 on 2026-08-08 13:11

from django.db import migrations


def seed_org_profile(apps, schema_editor):
    """Copy the first Advertisement's company block into OrgProfile once.

    Self-contained (no app imports): migrations must not depend on code that
    evolves. Runs before the legacy columns are dropped.
    """
    OrgProfile = apps.get_model("recruitment", "OrgProfile")
    if OrgProfile.objects.exists():
        return
    Advertisement = apps.get_model("recruitment", "Advertisement")
    advt = Advertisement.objects.order_by("id").first()
    if advt is not None:
        OrgProfile.objects.create(
            name_en=advt.company_name or "",
            name_hi="",
            tagline_en=advt.company_tagline or "",
            tagline_hi="",
            address=advt.company_address or "",
            contact_email=advt.contact_email or "",
            sbi_epay_text=advt.registration_fee_text or "",
        )
    else:
        OrgProfile.objects.create(name_en=schema_editor.connection.schema_name)


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_orgprofile'),
    ]

    operations = [
        migrations.RunPython(seed_org_profile, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='advertisement',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='company_tagline',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='registration_fee_text',
        ),
    ]
