# Generated by Django 6.0.7 on 2026-08-09 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0010_remove_advertisement_company_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='age_cutoff_date',
            field=models.DateField(blank=True, help_text='Reference date against which age limits are computed (e.g. advertisement closing date).', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum years of relevant experience required.', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='min_education_level',
            field=models.CharField(blank=True, choices=[('x', 'Class X'), ('xii', 'Class XII'), ('diploma', 'Diploma'), ('graduate', 'Graduate'), ('pg', 'Post Graduate'), ('phd', 'PhD')], help_text='Minimum education level required for the post.', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='min_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum aggregate percentage required (e.g. 60.00).', max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='EligibilityOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.BooleanField(help_text='Final eligibility verdict after human review (True = eligible).')),
                ('reason', models.TextField(help_text='Justification recorded by the overrider.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_override', to='recruitment.application')),
                ('overridden_by', models.ForeignKey(blank=True, help_text='User who recorded the override.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eligibility Override',
                'ordering': ['-created_at'],
            },
        ),
    ]
