# Generated by Django 6.0.7 on 2026-08-09 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0011_post_age_cutoff_date_post_experience_years_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostBasedRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_start_year', models.PositiveIntegerField(help_text='Calendar year in which this roster cycle began.')),
                ('roster_points', models.JSONField(default=list, help_text="Ordered 100-point roster: [{'serial', 'category', 'point_type'}, ...].")),
                ('current_position', models.PositiveIntegerField(default=1, help_text='Next serial in the roster to be filled.')),
                ('certified_on', models.DateTimeField(blank=True, help_text='When the roster was last certified.', null=True)),
                ('certified_by', models.ForeignKey(blank=True, help_text='User who certified the roster cycle.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_certified', to=settings.AUTH_USER_MODEL)),
                ('liaison_officer', models.ForeignKey(blank=True, help_text='Officer responsible for maintaining this roster.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_liaison_for', to=settings.AUTH_USER_MODEL)),
                ('post', models.OneToOneField(help_text='Post this roster cycle belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='roster', to='recruitment.post')),
            ],
            options={
                'verbose_name': 'Post Based Roster',
                'ordering': ['-cycle_start_year'],
            },
        ),
    ]
