# Generated by Django 6.0.7 on 2026-08-09 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0012_postbasedroster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Fee amount in INR.', max_digits=10)),
                ('gateway', models.CharField(help_text='Payment gateway used (e.g. mock, razorpay).', max_length=50)),
                ('gateway_ref', models.CharField(blank=True, help_text='Gateway-side payment/order ID for reconciliation.', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('exempt', models.BooleanField(default=False, help_text='True when the candidate is exempt from the fee.')),
                ('exempt_reason', models.TextField(blank=True, help_text='Human-readable reason for exemption.')),
                ('paid_at', models.DateTimeField(blank=True, help_text='Timestamp when payment was confirmed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(help_text='Application this payment is for.', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='recruitment.application')),
            ],
            options={
                'verbose_name': 'Payment',
                'ordering': ['-created_at'],
            },
        ),
    ]
