# Generated by Django 6.0.7 on 2026-08-09 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0013_payment_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(help_text='Name of the post being requested.', max_length=200)),
                ('count', models.PositiveIntegerField(help_text='Number of positions requested.')),
                ('grade', models.CharField(help_text='Pay grade (e.g. E-5).', max_length=20)),
                ('justification', models.TextField(help_text='Business justification for the requisition.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff user who raised this requisition.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vacancy Requisition',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('hod', 'Head of Department'), ('hr', 'HR Review'), ('finance', 'Finance'), ('final', 'Final Approval')], help_text='Approval stage (hod, hr, finance, final).', max_length=20)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True, help_text="Approver's comments.")),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(blank=True, help_text='Staff user who made the decision.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition_approvals', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(help_text='Requisition being approved.', on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='recruitment.vacancyrequisition')),
            ],
            options={
                'verbose_name': 'Requisition Approval',
                'ordering': ['timestamp'],
                'unique_together': {('requisition', 'stage')},
            },
        ),
    ]
