# Generated by Django 6.0.7

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0014_vacancy_requisition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corrigendum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(help_text='Sequential version number within the advertisement.')),
                ('changes_text', models.TextField(help_text='Description of what changed.')),
                ('published_date', models.DateField(help_text='Date the corrigendum was published.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to soft-hide without deleting.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advertisement', models.ForeignKey(help_text='Advertisement this corrigendum corrects.', on_delete=django.db.models.deletion.CASCADE, related_name='corrigenda', to='recruitment.advertisement')),
            ],
            options={
                'verbose_name': 'Corrigendum',
                'verbose_name_plural': 'Corrigenda',
                'ordering': ['-published_date'],
                'unique_together': {('advertisement', 'version')},
            },
        ),
    ]
