# Generated by Django 6.0.8

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0015_corrigendum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', help_text='Current verification status.', max_length=10)),
                ('comments', models.TextField(blank=True, help_text="Verifier's notes or rejection reason.")),
                ('verified_at', models.DateTimeField(blank=True, help_text='Timestamp of the verify/reject action.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(help_text='The document under review.', on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='recruitment.document')),
                ('verifier', models.ForeignKey(blank=True, help_text='Staff user who verified or rejected the document.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Verification',
                'verbose_name_plural': 'Document Verifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
