# Generated by Django 6.0.7 on 2026-08-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0016_documentverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyrequisition',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('finance_approved', 'Finance Approved'), ('reservation_certified', 'Reservation Certified'), ('ca_approved', 'CA Approved'), ('rejected', 'Rejected')], default='draft', max_length=30),
        ),
    ]
