# Generated by Django 6.0.7 on 2026-08-09 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0017_alter_vacancyrequisition_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Panel identifier (e.g. 'Panel A').", max_length=200)),
                ('external_members', models.JSONField(blank=True, default=list, help_text='External panel members as list of dicts (name, org, etc.).')),
                ('sitting_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Sitting fee per member (null if not applicable).', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(blank=True, help_text='Staff users serving on this panel.', related_name='interview_panels', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(help_text='Post this panel interviews for.', on_delete=django.db.models.deletion.CASCADE, related_name='interview_panels', to='recruitment.post')),
            ],
            options={
                'verbose_name': 'Interview Panel',
                'verbose_name_plural': 'Interview Panels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(help_text='Scheduled date and time of the interview.')),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='Duration of the interview in minutes.')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', help_text='Current status of the slot.', max_length=15)),
                ('notes', models.TextField(blank=True, help_text='Scheduling or logistics notes.')),
                ('application', models.ForeignKey(help_text='Application being interviewed.', on_delete=django.db.models.deletion.CASCADE, related_name='interview_slots', to='recruitment.application')),
                ('panel', models.ForeignKey(help_text='Panel conducting the interview.', on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='recruitment.interviewpanel')),
            ],
            options={
                'verbose_name': 'Interview Slot',
                'verbose_name_plural': 'Interview Slots',
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='InterviewScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, help_text='Score awarded (e.g. 7.5).', max_digits=4)),
                ('comments', models.TextField(blank=True, help_text="Panel member's comments or justification.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('panel_member', models.ForeignKey(blank=True, help_text='Panel member who gave the score (null for anonymous/external).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_scores', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(help_text='Interview slot this score belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='recruitment.interviewslot')),
            ],
            options={
                'verbose_name': 'Interview Score',
                'verbose_name_plural': 'Interview Scores',
                'ordering': ['-created_at'],
            },
        ),
    ]
