# Generated by Django 6.0.7 on 2026-08-09 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0018_interview_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='LitigationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(help_text='Court case number (e.g. WP/1234/2026).', max_length=100)),
                ('court', models.CharField(help_text='Court name (e.g. Gauhati High Court).', max_length=200)),
                ('petitioner', models.CharField(help_text='Name of the petitioner.', max_length=200)),
                ('status', models.CharField(choices=[('filed', 'Filed'), ('hearing', 'Hearing'), ('stay', 'Stay Granted'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='filed', help_text='Current status of the case.', max_length=20)),
                ('interim_orders', models.JSONField(blank=True, default=list, help_text='List of interim orders (type, date, text).')),
                ('final_order_text', models.TextField(blank=True, help_text='Text of the final court order.')),
                ('filed_on', models.DateField(help_text='Date the case was filed.')),
                ('resolved_on', models.DateField(blank=True, help_text='Date the case was resolved (null if still active).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advertisement', models.ForeignKey(blank=True, help_text='Linked advertisement (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litigation_cases', to='recruitment.advertisement')),
                ('application', models.ForeignKey(blank=True, help_text='Linked application (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litigation_cases', to='recruitment.application')),
                ('post', models.ForeignKey(blank=True, help_text='Linked post (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litigation_cases', to='recruitment.post')),
            ],
            options={
                'verbose_name': 'Litigation Case',
                'verbose_name_plural': 'Litigation Cases',
                'ordering': ['-filed_on'],
            },
        ),
    ]
