# Generated by Django 6.0.8 on 2026-08-09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0019_litigation_cases'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Brief subject of the grievance.', max_length=300)),
                ('description', models.TextField(help_text='Detailed description of the grievance.')),
                ('status', models.CharField(choices=[('filed', 'Filed'), ('acknowledged', 'Acknowledged'), ('investigating', 'Investigating'), ('resolved', 'Resolved')], default='filed', help_text='Current workflow status.', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes on the resolution outcome.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, help_text='Related application (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grievances', to='recruitment.application')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff member assigned to handle this grievance.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_grievances', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(help_text='Candidate who filed the grievance.', on_delete=django.db.models.deletion.CASCADE, related_name='grievances', to='recruitment.candidate')),
            ],
            options={
                'verbose_name': 'Grievance',
                'verbose_name_plural': 'Grievances',
                'ordering': ['-created_at'],
            },
        ),
    ]
