# Generated by Django 6.0.8 on 2026-08-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0019_litigation_cases'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoiningReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateField(help_text='Date the candidate reported for duty.')),
                ('designation', models.CharField(help_text='Designation at the time of joining (e.g. Assistant Engineer).', max_length=200)),
                ('pay_fixation', models.CharField(blank=True, default='', help_text='Pay fixation details (e.g. Level-7, ₹44,900/- in Pay Matrix).', max_length=200)),
                ('reported_to', models.CharField(help_text='Name and/or designation of the officer reported to.', max_length=200)),
                ('documents_submitted', models.BooleanField(default=False, help_text='Whether all required documents have been submitted at joining.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(help_text='The application this joining report belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='joining_report', to='recruitment.application')),
            ],
            options={
                'verbose_name': 'Joining Report',
                'verbose_name_plural': 'Joining Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
