# Generated by Django 6.0.8 on 2026-08-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0019_litigation_cases'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Date the probation period begins.')),
                ('end_date', models.DateField(help_text='Date the probation period ends.')),
                ('confirmed_on', models.DateField(blank=True, help_text='Date the employee was confirmed (null if still on probation).', null=True)),
                ('bond_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Bond amount in INR, if applicable.', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, help_text='Free-text notes about the probation or bond.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(help_text='The application this probation record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='probation_record', to='recruitment.application')),
            ],
            options={
                'verbose_name': 'Probation Record',
                'verbose_name_plural': 'Probation Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
