# Generated by Django 6.0.8 on 2026-08-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0020_probation_record'),
        ('recruitment', '0020_grievance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(help_text='Hospital or medical facility name.', max_length=300)),
                ('exam_date', models.DateField(help_text='Scheduled or actual date of the medical examination.')),
                ('report_file', models.FileField(blank=True, help_text='Uploaded medical report (PDF/image).', upload_to='medical_reports/%Y/%m/')),
                ('fitness_status', models.CharField(choices=[('pending', 'Pending'), ('fit', 'Fit'), ('unfit', 'Unfit')], default='pending', help_text='Fitness certification outcome.', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or remarks about the medical exam.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(help_text='The application this medical exam is for.', on_delete=django.db.models.deletion.CASCADE, related_name='medical_exams', to='recruitment.application')),
            ],
            options={
                'verbose_name': 'Medical Exam',
                'verbose_name_plural': 'Medical Exams',
                'ordering': ['-created_at'],
            },
        ),
    ]
