# Generated by Django 6.0.7 on 2026-08-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0020_grievance'),
        ('recruitment', '0020_joiningreport'),
        ('recruitment', '0020_probation_record'),
        ('recruitment', '0021_medical_exam'),
    ]

    operations = [
    ]
