# Generated by Django 6.0.7 on 2026-08-09 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0022_merge_phase4'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(help_text="Police district responsible for the verification (e.g. 'East Khasi Hills').", max_length=200)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('cleared', 'Cleared'), ('not_cleared', 'Not Cleared')], default='initiated', help_text='Current verification status.', max_length=15)),
                ('report_file', models.FileField(blank=True, help_text='Scanned police clearance report (PDF/image).', upload_to='police_reports/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or remarks.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(help_text='Application under police verification.', on_delete=django.db.models.deletion.CASCADE, related_name='police_verifications', to='recruitment.application')),
                ('initiated_by', models.ForeignKey(blank=True, help_text='Staff member who initiated the verification.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_police_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Police Verification',
                'verbose_name_plural': 'Police Verifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
