# Generated by Django 6.0.7 on 2026-08-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManpowerRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('executives', models.PositiveIntegerField(default=0)),
                ('supervisors', models.PositiveIntegerField(default=0)),
                ('workmen', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('primary_drivers', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['period_start'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('advertisement_window_start', models.DateField()),
                ('advertisement_window_end', models.DateField()),
                ('target_posts', models.PositiveIntegerField()),
                ('expected_joining_start', models.DateField()),
                ('expected_joining_end', models.DateField()),
                ('purpose', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['advertisement_window_start'],
            },
        ),
        migrations.CreateModel(
            name='RetirementForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('executives', models.PositiveIntegerField(default=0)),
                ('supervisors', models.PositiveIntegerField(default=0)),
                ('workmen', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['year'],
            },
        ),
    ]
