# Generated by Django 6.0.7 on 2026-08-04 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('application', 'Application Processing'), ('digilocker', 'DigiLocker Document Fetch'), ('interview', 'Interview Recording'), ('background_check', 'Background Verification'), ('resume_parsing', 'Resume Parsing'), ('data_retention', 'Data Retention')], max_length=40)),
                ('scope_text', models.TextField(blank=True, help_text='Plain-language description of what data is used and why.')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('candidate_portal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='portal.candidateportaluser')),
            ],
            options={
                'ordering': ['-granted_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('granted', 'Granted'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('viewed', 'Viewed'), ('updated', 'Updated')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Human actor, if any. System actions have None.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('consent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='consent.consent')),
            ],
            options={
                'verbose_name': 'Consent Event',
                'ordering': ['timestamp'],
            },
        ),
    ]
