# Generated by Django 6.0.7 on 2026-08-07 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0001_initial'),
        ('recruitment', '0004_advertisement_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='application',
            field=models.ForeignKey(blank=True, help_text='The application/post this consent is linked to, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consents', to='recruitment.application'),
        ),
    ]
