from django.urls import path
from . import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("advertisements/", views.advertisement_list, name="advertisement_list"),
    path("advertisements/create/", views.advertisement_create, name="advertisement_create"),
    path("advertisements/<int:advt_id>/", views.advertisement_detail, name="advertisement_detail"),
    path("advertisements/<int:advt_id>/generate/", views.advertisement_generate, name="advertisement_generate"),
    path("advertisements/<int:advt_id>/pdf/", views.advertisement_pdf, name="advertisement_pdf"),
    path("advertisements/<int:advt_id>/report/", views.advertisement_report, name="advertisement_report"),
    path("advertisements/<int:advt_id>/newspaper/", views.newspaper_preview, name="newspaper_preview"),
    path("advertisements/<int:advt_id>/corrigendum/", views.corrigendum_create, name="corrigendum_create"),
    path("applications/", views.application_list, name="application_list"),
    path("applications/export/", views.applications_export, name="applications_export"),
    path("applications/<str:application_id>/", views.application_detail, name="application_detail"),
    path("applications/<str:application_id>/eligibility/", views.run_eligibility, name="run_eligibility"),
    path("applications/<str:application_id>/offer/", views.offer_letter, name="offer_letter"),
    path("applications/<str:application_id>/communications/", views.communications, name="communications"),
    path("applications/<str:application_id>/digilocker-fetch/", views.digilocker_fetch, name="digilocker_fetch"),
    path("roster/<int:post_id>/", views.roster_view, name="roster_view"),
    path("shortlist/<int:post_id>/", views.shortlist_view, name="shortlist_view"),
    path("panel/<int:post_id>/", views.panel_view, name="panel_view"),
    path("panel/<int:post_id>/promote/<int:panel_id>/", views.panel_promote, name="panel_promote"),
    path("internal-postings/", views.internal_posting_list, name="internal_posting_list"),
    path("duplicates/", views.duplicates_queue, name="duplicates_queue"),
    path("duplicates/<int:flag_id>/resolve/", views.duplicates_resolve, name="duplicates_resolve"),
    path("analytics/", views.analytics_view, name="analytics"),
    path("fee-reconciliation/", views.fee_reconciliation, name="fee_reconciliation"),
    path("audit/consents/", views.consent_ledger, name="consent_ledger"),
    path("audit/consents/export/", views.consent_ledger_export, name="consent_ledger_export"),
    path("verify-documents/", views.verify_documents, name="verify_documents"),
    path("document-verification/dashboard/", views.document_verification_dashboard, name="document_verification_dashboard"),
    # Vacancy Requisition & Approval Workflow
    path("requisitions/", views.requisition_list, name="requisition_list"),
    path("requisitions/create/", views.requisition_create, name="requisition_create"),
    path("requisitions/<int:req_id>/", views.requisition_detail, name="requisition_detail"),
    path("requisitions/<int:req_id>/approve/", views.requisition_approve, name="requisition_approve"),
    # Fairness dashboard
    path("fairness/", views.fairness_dashboard, name="fairness_dashboard"),
    # Litigation
    path("litigation/", views.litigation_list, name="litigation_list"),
    path("litigation/<int:case_id>/add-order/", views.litigation_add_order, name="litigation_add_order"),
    path("litigation/<int:case_id>/update-status/", views.litigation_update_status, name="litigation_update_status"),
    # Interview workflow
    path("posts/<int:post_id>/interview/panel/create/", views.interview_panel_create, name="interview_panel_create"),
    path("interview/panel/<int:panel_id>/schedule/", views.interview_schedule, name="interview_schedule"),
    path("interview/slot/<int:slot_id>/score/", views.interview_score, name="interview_score"),
    path("posts/<int:post_id>/interview/results/", views.interview_results, name="interview_results"),
]
