# Generated by Django 6.0.7 on 2026-08-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('portal', 'Portal')], max_length=20)),
                ('to', models.CharField(help_text='Recipient (phone, email, or user id)', max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('portal', 'Portal')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body_template', models.TextField(help_text='Body text; use {variable} placeholders.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
